package modernworld

import (
	_ "embed"
	"strconv"
	"strings"
)

// Generated by tools/extract_spell_ranks.py from AzerothCore WotLK rank data.
// Unknown/custom IDs have no inferred relationship. This is independent of
// spell visuals and requires no database connection at runtime.
//
//go:embed spell_ranks_wotlk.csv
var spellRankCSV string

type spellRank struct{ first, rank uint32 }

var spellRanks = func() map[uint32]spellRank {
	ranks := make(map[uint32]spellRank)
	for _, line := range strings.Split(strings.TrimSpace(spellRankCSV), "\n")[1:] {
		fields := strings.Split(line, ",")
		if len(fields) != 3 {
			panic("invalid embedded spell rank row")
		}
		var values [3]uint32
		for i, field := range fields {
			n, err := strconv.ParseUint(strings.TrimSpace(field), 10, 32)
			if err != nil || n == 0 {
				panic("invalid embedded spell rank value")
			}
			values[i] = uint32(n)
		}
		if _, exists := ranks[values[0]]; exists {
			panic("duplicate embedded spell rank")
		}
		ranks[values[0]] = spellRank{values[1], values[2]}
	}
	return ranks
}()

// IsLowerSpellRank verifies a directional relationship, never a visual/name
// similarity. Callers must still establish cast ownership and packet phase.
func IsLowerSpellRank(requested, received uint32) bool {
	a, aOK := spellRanks[requested]
	b, bOK := spellRanks[received]
	return aOK && bOK && a.first == b.first && b.rank < a.rank
}
